
package com.huawei.unitypay;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnityPay", targetNamespace = "http://huawei.com/UnityPay/", wsdlLocation = "http://apay.gotoai.net/axis2/services/UnityPay?wsdl")
public class UnityPay_Service
    extends Service
{

    private final static URL UNITYPAY_WSDL_LOCATION;
    private final static WebServiceException UNITYPAY_EXCEPTION;
    private final static QName UNITYPAY_QNAME = new QName("http://huawei.com/UnityPay/", "UnityPay");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://apay.gotoai.net/axis2/services/UnityPay?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNITYPAY_WSDL_LOCATION = url;
        UNITYPAY_EXCEPTION = e;
    }

    public UnityPay_Service() {
        super(__getWsdlLocation(), UNITYPAY_QNAME);
    }

    public UnityPay_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNITYPAY_QNAME, features);
    }

    public UnityPay_Service(URL wsdlLocation) {
        super(wsdlLocation, UNITYPAY_QNAME);
    }

    public UnityPay_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNITYPAY_QNAME, features);
    }

    public UnityPay_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnityPay_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UnityPay
     */
    @WebEndpoint(name = "UnityPaySOAP")
    public UnityPay getUnityPaySOAP() {
        return super.getPort(new QName("http://huawei.com/UnityPay/", "UnityPaySOAP"), UnityPay.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnityPay
     */
    @WebEndpoint(name = "UnityPaySOAP")
    public UnityPay getUnityPaySOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://huawei.com/UnityPay/", "UnityPaySOAP"), UnityPay.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNITYPAY_EXCEPTION!= null) {
            throw UNITYPAY_EXCEPTION;
        }
        return UNITYPAY_WSDL_LOCATION;
    }

}
