
package com.huawei.unitypay;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UnityPay", targetNamespace = "http://huawei.com/UnityPay/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnityPay {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.BackPInvoiceRbResponse
     */
    @WebMethod(action = "http://huawei.com/UnityPay/backPInvoiceRb")
    @WebResult(name = "backPInvoiceRbResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public BackPInvoiceRbResponse backPInvoiceRb(
        @WebParam(name = "backPInvoiceRbRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        BackPInvoiceRbRequest parameters);

    /**
     * 
     * @param requestTime
     * @param result
     * @param indentCharge
     * @param charge
     * @param platId
     * @param requestId
     * @param responseTime
     * @param payIndentId
     * @param channelId
     * @param staffId
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/IndentItemQry")
    @RequestWrapper(localName = "indentItemQry", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentItemQry")
    @ResponseWrapper(localName = "indentItemQryResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentItemQryResponse")
    public void indentItemQry(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> platId,
        @WebParam(name = "channelId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> channelId,
        @WebParam(name = "payIndentId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> payIndentId,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "staffId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> staffId,
        @WebParam(name = "indentCharge", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> indentCharge,
        @WebParam(name = "Charge", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> charge,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.GetInvoiceResponse
     */
    @WebMethod(action = "http://huawei.com/UnityPay/getInvoice")
    @WebResult(name = "getInvoiceResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetInvoiceResponse getInvoice(
        @WebParam(name = "getInvoiceRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        GetInvoiceRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.PrintInvoiceResponse
     */
    @WebMethod(action = "http://huawei.com/UnityPay/printInvoice")
    @WebResult(name = "printInvoiceResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public PrintInvoiceResponse printInvoice(
        @WebParam(name = "printInvoiceRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        PrintInvoiceRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.IndentEleInvPrintResponse
     */
    @WebMethod(operationName = "IndentEleInvPrint", action = "http://huawei.com/UnityPay/IndentEleInvPrint")
    @WebResult(name = "IndentEleInvPrintResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public IndentEleInvPrintResponse indentEleInvPrint(
        @WebParam(name = "IndentEleInvPrintRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        IndentEleInvPrintRequest parameters);

    /**
     * 
     * @param responseTime
     * @param cycleId
     * @param payIndentId
     * @param custName
     * @param requestTime
     * @param result
     * @param custTaxFlag
     * @param platId
     * @param requestId
     * @param custType
     * @param custId
     * @param itemList
     * @param channelId
     * @param staffId
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/indentItemSync")
    @RequestWrapper(localName = "indentItemSync", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentItemSync")
    @ResponseWrapper(localName = "indentItemSyncResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentItemSyncResponse")
    public void indentItemSync(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "channelId", targetNamespace = "")
        String channelId,
        @WebParam(name = "cycleId", targetNamespace = "")
        int cycleId,
        @WebParam(name = "payIndentId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> payIndentId,
        @WebParam(name = "custType", targetNamespace = "")
        String custType,
        @WebParam(name = "custId", targetNamespace = "")
        String custId,
        @WebParam(name = "custName", targetNamespace = "")
        String custName,
        @WebParam(name = "custTaxFlag", targetNamespace = "")
        int custTaxFlag,
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "itemList", targetNamespace = "")
        ItemListType itemList,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

    /**
     * 
     * @param responseTime
     * @param cycleId
     * @param payIndentId
     * @param payList
     * @param custName
     * @param prepayFlag
     * @param payIdentId
     * @param requestTime
     * @param result
     * @param custTaxFlag
     * @param platId
     * @param interfaceSerial
     * @param requestId
     * @param custType
     * @param custId
     * @param itemList
     * @param channelId
     * @param staffId
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/indentItemPay")
    @RequestWrapper(localName = "indentItemPay", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentItemPay")
    @ResponseWrapper(localName = "indentItemPayResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentItemPayResponse")
    public void indentItemPay(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "channelId", targetNamespace = "")
        String channelId,
        @WebParam(name = "cycleId", targetNamespace = "")
        int cycleId,
        @WebParam(name = "payIdentId", targetNamespace = "")
        String payIdentId,
        @WebParam(name = "custType", targetNamespace = "")
        String custType,
        @WebParam(name = "custId", targetNamespace = "")
        String custId,
        @WebParam(name = "custName", targetNamespace = "")
        String custName,
        @WebParam(name = "custTaxFlag", targetNamespace = "")
        int custTaxFlag,
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "interfaceSerial", targetNamespace = "")
        String interfaceSerial,
        @WebParam(name = "prepayFlag", targetNamespace = "")
        String prepayFlag,
        @WebParam(name = "itemList", targetNamespace = "")
        PayItemListType itemList,
        @WebParam(name = "payList", targetNamespace = "")
        PayListType payList,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "payIndentId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> payIndentId,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

    /**
     * 
     * @param agentId
     * @param responseTime
     * @param cycleId
     * @param agentName
     * @param payIndentId
     * @param totalChargeGet
     * @param totalCount
     * @param requestTime
     * @param result
     * @param totalCharge
     * @param custTaxFlag
     * @param platId
     * @param requestId
     * @param itemList
     * @param channelId
     * @param staffId
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/batchIndentItemSync")
    @RequestWrapper(localName = "batchIndentItemSync", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.BatchIndentItemSync")
    @ResponseWrapper(localName = "batchIndentItemSyncResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.BatchIndentItemSyncResponse")
    public void batchIndentItemSync(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "channelId", targetNamespace = "")
        String channelId,
        @WebParam(name = "cycleId", targetNamespace = "")
        String cycleId,
        @WebParam(name = "payIndentId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> payIndentId,
        @WebParam(name = "agentId", targetNamespace = "")
        String agentId,
        @WebParam(name = "agentName", targetNamespace = "")
        String agentName,
        @WebParam(name = "totalCharge", targetNamespace = "")
        String totalCharge,
        @WebParam(name = "custTaxFlag", targetNamespace = "")
        int custTaxFlag,
        @WebParam(name = "totalChargeGet", targetNamespace = "")
        String totalChargeGet,
        @WebParam(name = "totalCount", targetNamespace = "")
        String totalCount,
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "itemList", targetNamespace = "")
        BatchSyncItemListType itemList,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

    /**
     * 
     * @param phoneNbr
     * @param printType
     * @param responseTime
     * @param cycleId
     * @param payIndentId
     * @param invoiceLists
     * @param requestTime
     * @param result
     * @param platId
     * @param requestId
     * @param invoiceType
     * @param invoiceId
     * @param staffId
     * @param channelId
     * @param email
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/indentInvoicePrint")
    @RequestWrapper(localName = "indentInvoicePrint", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoicePrint")
    @ResponseWrapper(localName = "indentInvoicePrintResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoicePrintResponse")
    public void indentInvoicePrint(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "cycleId", targetNamespace = "")
        int cycleId,
        @WebParam(name = "payIndentId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> payIndentId,
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "printType", targetNamespace = "")
        int printType,
        @WebParam(name = "invoiceType", targetNamespace = "")
        int invoiceType,
        @WebParam(name = "invoiceId", targetNamespace = "")
        String invoiceId,
        @WebParam(name = "channelId", targetNamespace = "")
        String channelId,
        @WebParam(name = "phoneNbr", targetNamespace = "")
        String phoneNbr,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result,
        @WebParam(name = "invoiceLists", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<InvoiceListType>> invoiceLists);

    /**
     * 
     * @param requestTime
     * @param result
     * @param platId
     * @param invoiceNbr
     * @param requestId
     * @param responseTime
     * @param cycleId
     * @param invoiceType
     * @param staffId
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/indentInvoiceNumQry")
    @RequestWrapper(localName = "indentInvoiceNumQry", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoiceNumQry")
    @ResponseWrapper(localName = "indentInvoiceNumQryResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoiceNumQryResponse")
    public void indentInvoiceNumQry(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "cycleId", targetNamespace = "")
        int cycleId,
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "invoiceType", targetNamespace = "")
        int invoiceType,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result,
        @WebParam(name = "invoiceNbr", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> invoiceNbr);

    /**
     * 
     * @param requestTime
     * @param result
     * @param platId
     * @param requestId
     * @param responseTime
     * @param cycleId
     * @param invoiceType
     * @param invoiceId
     * @param staffId
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/indentInvoiceNumMod")
    @RequestWrapper(localName = "indentInvoiceNumMod", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoiceNumMod")
    @ResponseWrapper(localName = "indentInvoiceNumModResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoiceNumModResponse")
    public void indentInvoiceNumMod(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "cycleId", targetNamespace = "")
        int cycleId,
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "invoiceType", targetNamespace = "")
        int invoiceType,
        @WebParam(name = "invoiceId", targetNamespace = "")
        String invoiceId,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

    /**
     * 
     * @param requestTime
     * @param result
     * @param servId
     * @param instanceId
     * @param platId
     * @param requestId
     * @param responseTime
     * @param acctId
     * @param balanceList
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/prepayBack")
    @RequestWrapper(localName = "prepayBack", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.PrepayBack")
    @ResponseWrapper(localName = "prepayBackResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.PrepayBackResponse")
    public void prepayBack(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "servId", targetNamespace = "")
        String servId,
        @WebParam(name = "acctId", targetNamespace = "")
        String acctId,
        @WebParam(name = "instanceId", targetNamespace = "")
        String instanceId,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result,
        @WebParam(name = "balanceList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<BalanceListType>> balanceList);

    /**
     * 
     * @param exchangeDate
     * @param couponName
     * @param charge
     * @param bcdCode
     * @param auditTICKETCD
     * @param responseTime
     * @param staffidGen
     * @param staffidReverse
     * @param cycleId
     * @param payIndentId
     * @param remark
     * @param couponId
     * @param requestTime
     * @param result
     * @param facevalue
     * @param servId
     * @param platId
     * @param offerSpecName
     * @param requestId
     * @param accNbr
     * @param ticketGenDate
     * @param staffId
     * @param channelId
     * @param responseId
     */
    @WebMethod(operationName = "TerminalExchangeSync", action = "http://huawei.com/UnityPay/TerminalExchangeSync")
    @RequestWrapper(localName = "TerminalExchangeSync", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.TerminalExchangeSync")
    @ResponseWrapper(localName = "TerminalExchangeSyncResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.TerminalExchangeSyncResponse")
    public void terminalExchangeSync(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "cycleId", targetNamespace = "")
        int cycleId,
        @WebParam(name = "exchangeDate", targetNamespace = "")
        String exchangeDate,
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "channelId", targetNamespace = "")
        String channelId,
        @WebParam(name = "payIndentId", targetNamespace = "")
        String payIndentId,
        @WebParam(name = "AUDIT_TICKET_CD", targetNamespace = "")
        String auditTICKETCD,
        @WebParam(name = "facevalue", targetNamespace = "")
        String facevalue,
        @WebParam(name = "remark", targetNamespace = "")
        String remark,
        @WebParam(name = "charge", targetNamespace = "")
        int charge,
        @WebParam(name = "servId", targetNamespace = "")
        String servId,
        @WebParam(name = "accNbr", targetNamespace = "")
        String accNbr,
        @WebParam(name = "ticketGenDate", targetNamespace = "")
        String ticketGenDate,
        @WebParam(name = "couponName", targetNamespace = "")
        String couponName,
        @WebParam(name = "couponId", targetNamespace = "")
        String couponId,
        @WebParam(name = "bcdCode", targetNamespace = "")
        String bcdCode,
        @WebParam(name = "staffidGen", targetNamespace = "")
        String staffidGen,
        @WebParam(name = "staffidReverse", targetNamespace = "")
        String staffidReverse,
        @WebParam(name = "offerSpecName", targetNamespace = "")
        String offerSpecName,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

    /**
     * 
     * @param requestTime
     * @param result
     * @param platId
     * @param requestId
     * @param responseTime
     * @param payIndentId
     * @param responseId
     */
    @WebMethod(operationName = "IndentInvoiceQuery", action = "http://huawei.com/UnityPay/IndentInvoiceQuery")
    @RequestWrapper(localName = "IndentInvoiceQuery", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoiceQuery")
    @ResponseWrapper(localName = "IndentInvoiceQueryResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoiceQueryResponse")
    public void indentInvoiceQuery(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "payIndentId", targetNamespace = "")
        String payIndentId,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

    /**
     * 
     * @param requestTime
     * @param result
     * @param staffCode
     * @param platId
     * @param requestId
     * @param responseTime
     * @param invoiceType
     * @param payIndentId
     * @param invoiceLists
     * @param responseId
     */
    @WebMethod(operationName = "IndentInvoiceRepPrint", action = "http://huawei.com/UnityPay/IndentInvoiceRepPrint")
    @RequestWrapper(localName = "IndentInvoiceRepPrint", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoiceRepPrint")
    @ResponseWrapper(localName = "IndentInvoiceRepPrintResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentInvoiceRepPrintResponse")
    public void indentInvoiceRepPrint(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "payIndentId", targetNamespace = "")
        String payIndentId,
        @WebParam(name = "staffCode", targetNamespace = "")
        String staffCode,
        @WebParam(name = "invoiceType", targetNamespace = "")
        int invoiceType,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result,
        @WebParam(name = "InvoiceLists", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<InvoiceLists> invoiceLists);

    /**
     * 
     * @param requestTime
     * @param result
     * @param platId
     * @param requestId
     * @param responseTime
     * @param payIndentId
     * @param responseId
     */
    @WebMethod(action = "http://huawei.com/UnityPay/indentTaxQuery")
    @RequestWrapper(localName = "indentTaxQuery", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentTaxQuery")
    @ResponseWrapper(localName = "indentTaxQueryResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentTaxQueryResponse")
    public void indentTaxQuery(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "payIndentId", targetNamespace = "")
        String payIndentId,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.GetAcctInfoResponse
     */
    @WebMethod(action = "http://huawei.com/UnityPay/getAcctInfo")
    @WebResult(name = "getAcctInfoResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetAcctInfoResponse getAcctInfo(
        @WebParam(name = "getAcctInfoRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        GetAcctInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.PreprintInvoiceRbResponse
     */
    @WebMethod(action = "http://huawei.com/UnityPay/preprintInvoiceRb")
    @WebResult(name = "preprintInvoiceRbResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public PreprintInvoiceRbResponse preprintInvoiceRb(
        @WebParam(name = "preprintInvoiceRbRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        PreprintInvoiceRbRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.GetPreprintInvoiceResponse
     */
    @WebMethod(action = "http://huawei.com/UnityPay/getPreprintInvoice")
    @WebResult(name = "getPreprintInvoiceResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetPreprintInvoiceResponse getPreprintInvoice(
        @WebParam(name = "getPreprintInvoiceRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        GetPreprintInvoiceRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.PreprintInvoiceResponse
     */
    @WebMethod(action = "http://huawei.com/UnityPay/preprintInvoice")
    @WebResult(name = "preprintInvoiceResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public PreprintInvoiceResponse preprintInvoice(
        @WebParam(name = "preprintInvoiceRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        PreprintInvoiceRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.huawei.unitypay.VerifyDepositResponse
     */
    @WebMethod(action = "http://huawei.com/UnityPay/verifyDeposit")
    @WebResult(name = "verifyDepositResponse", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public VerifyDepositResponse verifyDeposit(
        @WebParam(name = "verifyDepositRequest", targetNamespace = "http://huawei.com/UnityPay/", partName = "parameters")
        VerifyDepositRequest parameters);

    /**
     * 
     * @param requestTime
     * @param result
     * @param amount
     * @param acctMonth
     * @param obj
     * @param errorMessage
     * @param errorCode
     * @param interfaceId
     * @param objType
     * @param invoiceLists
     */
    @WebMethod(action = "http://huawei.com/UnityPay/getInvoiceDetail")
    @RequestWrapper(localName = "getInvoiceDetail", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.GetInvoiceDetail")
    @ResponseWrapper(localName = "getInvoiceDetailResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.GetInvoiceDetailResponse")
    public void getInvoiceDetail(
        @WebParam(name = "objType", targetNamespace = "")
        String objType,
        @WebParam(name = "obj", targetNamespace = "")
        String obj,
        @WebParam(name = "acctMonth", targetNamespace = "")
        String acctMonth,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "interfaceId", targetNamespace = "")
        String interfaceId,
        @WebParam(name = "Result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> result,
        @WebParam(name = "errorCode", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> errorCode,
        @WebParam(name = "errorMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> errorMessage,
        @WebParam(name = "Amount", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> amount,
        @WebParam(name = "InvoiceLists", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<InvoiceDetailLists> invoiceLists);

    /**
     * 
     * @param requestStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://huawei.com/UnityPay/queryAgentPayableFund")
    @WebResult(name = "queryAgentPayableFundReturn", targetNamespace = "")
    @RequestWrapper(localName = "queryAgentPayableFund", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.QueryAgentPayableFund")
    @ResponseWrapper(localName = "queryAgentPayableFundResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.QueryAgentPayableFundResponse")
    public String queryAgentPayableFund(
        @WebParam(name = "requestStr", targetNamespace = "")
        String requestStr);

    /**
     * 
     * @param charge
     * @param responseTime
     * @param cycleId
     * @param payIndentId
     * @param payList
     * @param prepayFlag
     * @param requestTime
     * @param result
     * @param platId
     * @param requestId
     * @param channelId
     * @param staffId
     * @param responseId
     */
    @WebMethod(operationName = "IndentItemReCharge", action = "http://huawei.com/UnityPay/IndentItemReCharge")
    @RequestWrapper(localName = "IndentItemReCharge", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentItemReCharge")
    @ResponseWrapper(localName = "IndentItemReChargeResponse", targetNamespace = "http://huawei.com/UnityPay/", className = "com.huawei.unitypay.IndentItemReChargeResponse")
    public void indentItemReCharge(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestTime", targetNamespace = "")
        String requestTime,
        @WebParam(name = "platId", targetNamespace = "")
        String platId,
        @WebParam(name = "channelId", targetNamespace = "")
        String channelId,
        @WebParam(name = "cycleId", targetNamespace = "")
        int cycleId,
        @WebParam(name = "payIndentId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> payIndentId,
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "prepayFlag", targetNamespace = "")
        String prepayFlag,
        @WebParam(name = "charge", targetNamespace = "")
        String charge,
        @WebParam(name = "payList", targetNamespace = "")
        RechargePayListType payList,
        @WebParam(name = "responseId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseId,
        @WebParam(name = "responseTime", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> responseTime,
        @WebParam(name = "result", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> result);

}
